version: "2.1"
services:
  slave-processing:
    build:
      context: .
    scale: 2
    command: python3 processing.py
    environment:
      - PYTHONUNBUFFERED=1
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - slave-processing
    ports:
      - "5556:5556"
