version: "2.1"
services:
  jobmanager:
    build:
      context: flink
    expose:
      - "6123"
    ports:
      - "8081:8081"
      - "8089:8089"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS: jobmanager
    container_name: flink

  taskmanager:
    build:
      context: flink
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS: jobmanager
    links:
      - "jobmanager:jobmanager"
  
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
      
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zeppelin:
    image: apache/zeppelin:0.9.0
    container_name: zeppelin
    environment:
      - ZEPPELIN_NOTEBOOK_DIR: /notebook
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/notebook:/notebook"

